Traceback (most recent call last):
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import spacy

nlp = spacy.load("en_core_web_sm")

doc = nlp(example_sent)

pos_df = pd.DataFrame(
    [(token.text, token.lemma_, token.pos_, token.tag_) for token in doc],
    columns=["text", "lemma", "pos", "tag"],
)
pos_df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Input [0;32mIn [38][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mspacy[39;00m
[0;32m----> 3[0m nlp [38;5;241m=[39m [43mspacy[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43men_core_web_sm[39;49m[38;5;124;43m"[39;49m[43m)[49m
[1;32m      5[0m doc [38;5;241m=[39m nlp(example_sent)
[1;32m      7[0m pos_df [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(
[1;32m      8[0m     [(token[38;5;241m.[39mtext, token[38;5;241m.[39mlemma_, token[38;5;241m.[39mpos_, token[38;5;241m.[39mtag_) [38;5;28;01mfor[39;00m token [38;5;129;01min[39;00m doc],
[1;32m      9[0m     columns[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mtext[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mlemma[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mpos[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mtag[39m[38;5;124m"[39m],
[1;32m     10[0m )

File [0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/spacy/__init__.py:54[0m, in [0;36mload[0;34m(name, vocab, disable, enable, exclude, config)[0m
[1;32m     30[0m [38;5;28;01mdef[39;00m [38;5;21mload[39m(
[1;32m     31[0m     name: Union[[38;5;28mstr[39m, Path],
[1;32m     32[0m     [38;5;241m*[39m,
[0;32m   (...)[0m
[1;32m     37[0m     config: Union[Dict[[38;5;28mstr[39m, Any], Config] [38;5;241m=[39m util[38;5;241m.[39mSimpleFrozenDict(),
[1;32m     38[0m ) [38;5;241m-[39m[38;5;241m>[39m Language:
[1;32m     39[0m     [38;5;124;03m"""Load a spaCy model from an installed package or a local path.[39;00m
[1;32m     40[0m 
[1;32m     41[0m [38;5;124;03m    name (str): Package name or model path.[39;00m
[0;32m   (...)[0m
[1;32m     52[0m [38;5;124;03m    RETURNS (Language): The loaded nlp object.[39;00m
[1;32m     53[0m [38;5;124;03m    """[39;00m
[0;32m---> 54[0m     [38;5;28;01mreturn[39;00m [43mutil[49m[38;5;241;43m.[39;49m[43mload_model[49m[43m([49m
[1;32m     55[0m [43m        [49m[43mname[49m[43m,[49m
[1;32m     56[0m [43m        [49m[43mvocab[49m[38;5;241;43m=[39;49m[43mvocab[49m[43m,[49m
[1;32m     57[0m [43m        [49m[43mdisable[49m[38;5;241;43m=[39;49m[43mdisable[49m[43m,[49m
[1;32m     58[0m [43m        [49m[43menable[49m[38;5;241;43m=[39;49m[43menable[49m[43m,[49m
[1;32m     59[0m [43m        [49m[43mexclude[49m[38;5;241;43m=[39;49m[43mexclude[49m[43m,[49m
[1;32m     60[0m [43m        [49m[43mconfig[49m[38;5;241;43m=[39;49m[43mconfig[49m[43m,[49m
[1;32m     61[0m [43m    [49m[43m)[49m

File [0;32m/opt/anaconda3/envs/codeforecon/lib/python3.8/site-packages/spacy/util.py:436[0m, in [0;36mload_model[0;34m(name, vocab, disable, enable, exclude, config)[0m
[1;32m    434[0m [38;5;28;01mif[39;00m name [38;5;129;01min[39;00m OLD_MODEL_SHORTCUTS:
[1;32m    435[0m     [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m(Errors[38;5;241m.[39mE941[38;5;241m.[39mformat(name[38;5;241m=[39mname, full[38;5;241m=[39mOLD_MODEL_SHORTCUTS[name]))  [38;5;66;03m# type: ignore[index][39;00m
[0;32m--> 436[0m [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m(Errors[38;5;241m.[39mE050[38;5;241m.[39mformat(name[38;5;241m=[39mname))

[0;31mOSError[0m: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

